export const SSSP_HAZARD_LIBRARY = [
  {
    id: 'excavation-collapse',
    activity: 'Excavation / trenching',
    hazard: 'Trench wall collapse or cave-in',
    potentialHarm: 'Crush injuries, burial, fatality',
    initialLikelihood: 3,
    initialConsequence: 5,
    controls: 'Permit to dig, shoring/benching, service locate, exclusion zones, competent person inspection',
    controlHierarchy: 'engineering',
    criticalRiskId: 'excavations',
  },
  {
    id: 'underground-services',
    activity: 'Earthworks / excavation',
    hazard: 'Strike on underground services (power, gas, water, fibre)',
    potentialHarm: 'Electrocution, explosion, flooding, service outage',
    initialLikelihood: 3,
    initialConsequence: 5,
    controls: 'Dial-before-you-dig, hand dig near marks, service plans on site, spotter',
    controlHierarchy: 'administrative',
    criticalRiskId: 'services',
  },
  {
    id: 'mobile-plant-people',
    activity: 'Plant operation on site',
    hazard: 'Person struck by mobile plant or caught in swing zone',
    potentialHarm: 'Crush injuries, fatality',
    initialLikelihood: 4,
    initialConsequence: 5,
    controls: 'Exclusion zones, spotter, pre-start, reversing alarm, hi-vis, communication plan',
    controlHierarchy: 'engineering',
    criticalRiskId: 'mobile-plant',
  },
  {
    id: 'overhead-services',
    activity: 'Plant / tipper / crane work',
    hazard: 'Contact with overhead power lines',
    potentialHarm: 'Electrocution, burns, fatality',
    initialLikelihood: 2,
    initialConsequence: 5,
    controls: 'Approach limits, tiger tails, look up and live, spotter, route planning',
    controlHierarchy: 'engineering',
    criticalRiskId: 'services',
  },
  {
    id: 'traffic-interface',
    activity: 'Work adjacent to live traffic',
    hazard: 'Vehicle / pedestrian collision with work area',
    potentialHarm: 'Serious injury, fatality, public harm',
    initialLikelihood: 3,
    initialConsequence: 4,
    controls: 'TMP, cones/barriers, signage, spotters, reduced speed zones',
    controlHierarchy: 'engineering',
    criticalRiskId: 'traffic',
  },
  {
    id: 'unstable-ground',
    activity: 'Plant on slopes / fill / soft ground',
    hazard: 'Plant rollover or ground failure',
    potentialHarm: 'Crush injuries, rollover, fatality',
    initialLikelihood: 3,
    initialConsequence: 4,
    controls: 'Ground assessment, work uphill, reduce load, geotechnical advice if needed',
    controlHierarchy: 'engineering',
    criticalRiskId: 'unstable-ground',
  },
  {
    id: 'lifting-suspended',
    activity: 'Lifting / rigging operations',
    hazard: 'Suspended load drop or swing',
    potentialHarm: 'Crush injuries, fatality',
    initialLikelihood: 2,
    initialConsequence: 5,
    controls: 'Lift plan, inspected rigging, exclusion zone, tag lines, competent dogman',
    controlHierarchy: 'engineering',
    criticalRiskId: 'lifting',
  },
  {
    id: 'working-near-water',
    activity: 'Work near watercourse / pond / culvert',
    hazard: 'Drowning, bank collapse, sediment discharge',
    potentialHarm: 'Drowning, environmental harm, plant loss',
    initialLikelihood: 2,
    initialConsequence: 4,
    controls: 'Rescue plan, barriers, keep plant back from edges, sediment controls',
    controlHierarchy: 'administrative',
    criticalRiskId: 'water',
  },
  {
    id: 'confined-space',
    activity: 'Entry to pit, manhole, tank, trench >1.5m',
    hazard: 'Confined space — poor atmosphere, engulfment',
    potentialHarm: 'Asphyxiation, engulfment, fatality',
    initialLikelihood: 2,
    initialConsequence: 5,
    controls: 'Permit, atmospheric testing, standby/rescue, no entry without plan',
    controlHierarchy: 'administrative',
    criticalRiskId: 'confined-spaces',
  },
  {
    id: 'demolition-structural',
    activity: 'Demolition / structural alteration',
    hazard: 'Unplanned structural collapse',
    potentialHarm: 'Crush injuries, fatality',
    initialLikelihood: 2,
    initialConsequence: 5,
    controls: 'Engineer advice, sequence plan, exclusion zones, service isolation',
    controlHierarchy: 'engineering',
    criticalRiskId: 'demolition',
  },
  {
    id: 'manual-handling',
    activity: 'Manual handling / installation',
    hazard: 'Musculoskeletal injury from lifting or repetitive work',
    potentialHarm: 'Strain, sprain, long-term injury',
    initialLikelihood: 4,
    initialConsequence: 2,
    controls: 'Mechanical aids, team lifts, job rotation, training',
    controlHierarchy: 'engineering',
  },
  {
    id: 'noise-exposure',
    activity: 'Plant operation / compaction / breaking',
    hazard: 'Noise exposure above exposure limits',
    potentialHarm: 'Hearing loss, tinnitus',
    initialLikelihood: 4,
    initialConsequence: 2,
    controls: 'Hearing protection, rotation, maintenance, signage',
    controlHierarchy: 'ppe',
  },
  {
    id: 'dust-silica',
    activity: 'Cutting, drilling, dry excavation',
    hazard: 'Respirable dust / silica exposure',
    potentialHarm: 'Respiratory disease, silicosis',
    initialLikelihood: 3,
    initialConsequence: 4,
    controls: 'Water suppression, dust masks/respirators, enclosed cab, monitoring',
    controlHierarchy: 'engineering',
  },
  {
    id: 'fuel-chemical',
    activity: 'Refuelling / chemical use on site',
    hazard: 'Fuel spill, fire, chemical exposure',
    potentialHarm: 'Burns, fire, environmental harm, illness',
    initialLikelihood: 2,
    initialConsequence: 4,
    controls: 'Spill kit, bunding, SDS available, no smoking zones, training',
    controlHierarchy: 'administrative',
  },
  {
    id: 'heat-stress',
    activity: 'Outdoor work in hot conditions',
    hazard: 'Heat stress / dehydration',
    potentialHarm: 'Heat exhaustion, collapse',
    initialLikelihood: 3,
    initialConsequence: 3,
    controls: 'Hydration, shade/rest breaks, reschedule heavy work, buddy system',
    controlHierarchy: 'administrative',
  },
  {
    id: 'working-at-height',
    activity: 'Work on plant, stockpiles, edges',
    hazard: 'Fall from height',
    potentialHarm: 'Fractures, serious injury, fatality',
    initialLikelihood: 3,
    initialConsequence: 4,
    controls: 'Edge protection, harness where required, 3-point contact, no climbing on buckets',
    controlHierarchy: 'engineering',
  },
  {
    id: 'public-interface',
    activity: 'Public access near work zone',
    hazard: 'Member of public enters work area',
    potentialHarm: 'Serious injury to public, reputational/legal harm',
    initialLikelihood: 3,
    initialConsequence: 4,
    controls: 'Barriers, signage, escort, communication with residents/clients',
    controlHierarchy: 'administrative',
    criticalRiskId: 'traffic',
  },
  {
    id: 'night-work',
    activity: 'Night / low-light operations',
    hazard: 'Reduced visibility — plant/pedestrian collision',
    potentialHarm: 'Serious injury, fatality',
    initialLikelihood: 3,
    initialConsequence: 4,
    controls: 'Adequate lighting, hi-vis, reduced speed, spotters, TMP review',
    controlHierarchy: 'administrative',
  },
  {
    id: 'subcontractor-coord',
    activity: 'Multiple contractors on site',
    hazard: 'Interface hazards — overlapping work areas',
    potentialHarm: 'Collision, conflicting activities, injury',
    initialLikelihood: 3,
    initialConsequence: 3,
    controls: 'Site induction, daily coordination, shared SSSP, permits',
    controlHierarchy: 'administrative',
  },
  {
    id: 'utility-strikes',
    activity: 'Piling / anchoring / probing',
    hazard: 'Utility strike during penetration works',
    potentialHarm: 'Electrocution, gas release, service damage',
    initialLikelihood: 2,
    initialConsequence: 5,
    controls: 'Non-destructive locating, permit, hand prove, service owner on standby',
    controlHierarchy: 'administrative',
    criticalRiskId: 'services',
  },
  {
    id: 'stockpile-slip',
    activity: 'Working near stockpiles / spoil heaps',
    hazard: 'Stockpile slip or engulfment',
    potentialHarm: 'Burial, crush injuries',
    initialLikelihood: 2,
    initialConsequence: 4,
    controls: 'Keep distance, no undercutting, benching, barricades',
    controlHierarchy: 'engineering',
    criticalRiskId: 'unstable-ground',
  },
  {
    id: 'pressure-testing',
    activity: 'Pressure testing pipes / services',
    hazard: 'Sudden release of pressure',
    potentialHarm: 'Impact injury, eye injury',
    initialLikelihood: 2,
    initialConsequence: 3,
    controls: 'Exclusion zone, gradual pressurisation, inspected fittings, PPE',
    controlHierarchy: 'engineering',
  },
  {
    id: 'asbestos-unknown',
    activity: 'Demolition / soil import / old structures',
    hazard: 'Unexpected asbestos or hazardous material',
    potentialHarm: 'Long-term illness, regulatory breach',
    initialLikelihood: 2,
    initialConsequence: 4,
    controls: 'Survey before work, stop work if suspected, licensed removal',
    controlHierarchy: 'elimination',
    criticalRiskId: 'demolition',
  },
  {
    id: 'emergency-access',
    activity: 'Site setup / ongoing operations',
    hazard: 'Blocked emergency access / assembly point unclear',
    potentialHarm: 'Delayed emergency response, increased harm in incident',
    initialLikelihood: 2,
    initialConsequence: 4,
    controls: 'Marked access routes, assembly point signage, keep clear, brief all workers',
    controlHierarchy: 'administrative',
  },
]

export function getHazardTemplateById(id) {
  return SSSP_HAZARD_LIBRARY.find((item) => item.id === id) ?? null
}
